### ISSUE TITLE
根据过滤器例子使用logfilter时,会拦截了需要回调的远程方法。导致回调一直不生效

### ISSUE THREAD

**Issue by pkdog** [hprose/hprose-nodejs#12]
根据过滤器例子使用logfilter时,会拦截了需要回调的远程方法。导致回调一直不生效

**Comment by pkdog** [comment]
https://github.com/hprose/hprose-nodejs/tree/master/example/filter/log
log filter的例子能不能加上一些使用了回调函数的例子。

**Comment by andot** [comment]
你把不能生效的代码贴上来看一下可以吗？
