### ISSUE TITLE
client放置长时间后，回调不能执行

### ISSUE THREAD

**Issue by HC1988** [hprose/hprose-nodejs#13]
Hi，本人利用node-webkit在windows 7 ×64启动了一个hprose服务器(websocket),然后用nw启动了另外一个客户端（和服务不是一个进程），在放置一段时间（不到2小时）不使用后（之前正常），客户端调用服务端通过addAsyncFunction增加的方法，服务端可以正常收到消息执行，但是客户端的callback却不能被执行，请问这个问题怎么解决，还是我需要设置什么参数？

best wish!

**Comment by andot** [comment]
你在客户端加上异常回调看一下，有没有错误信息

**Comment by HC1988** [comment]
现在看来可能是电脑休眠导致websocket中断导致的，后面是否加入client重连的机制？ @andot

**Comment by andot** [comment]
客户端有重连机制。客户端有个 idempotent 属性，设置为 true，就可以自动重连。
