### ISSUE TITLE
Proxy.create和Proxy.createFunction这两个文件已经不在node版本里支持

### ISSUE THREAD

**Issue by jiangzhuo** [hprose/hprose-nodejs#15]
https://github.com/hprose/hprose-nodejs/blob/master/lib/client/Client.js#L51
可能作者写的client.js的时候比较早，现在的node的6.x版本和7.x版本都不再支持已经弃用的Proxy.create和createFunction
https://developer.mozilla.org/en-US/docs/Archive/Web/Old_Proxy_API
在ES2015正式的规范里已经确定使用new Proxy和handler了 希望作者能进行修改或者兼容。

**Comment by andot** [comment]
嗯，这个功能写的比较早，当时还不支持现在的方式。
