### ISSUE TITLE
Typescript下没法用了

### ISSUE THREAD

**Issue by gb-6k-house** [hprose/hprose-nodejs#24]
之前没有index.d.ts文件时候在Typescript可以使用。现在加了namespace之后，声明的类又没导出，请问在Typescript如何使用啊啊啊啊啊。

**Comment by andot** [comment]
你说的声明的类是什么？

**Comment by gb-6k-house** [comment]
更新最新的包在TS下就不行，还没仔细找原因。现在项目已经替换成gRPC了。。。

**Comment by gb-6k-house** [comment]
更新最新的包在TS下就不行，还没仔细找原因。现在项目已经替换成gRPC了。。。

**Comment by andot** [comment]
是 index.d.ts 文件有问题吗？这个我不懂，如果是它引起的，我把它删了算了。

**Comment by andot** [comment]
Hprose 3.0 for TypeScript 版本已经出来了，全部代码都是使用 TypeScript 编写的。不会在出现在 TypeScript 不能使用的问题了。
