### ISSUE TITLE
在监听情况下休眠电脑一段时间，会报错

### ISSUE THREAD

**Issue by zhangruhong** [hprose/hprose-nodejs#25]
![image](https://user-images.githubusercontent.com/7161770/42265827-3c8f2daa-7fa7-11e8-8611-af1c034e751e.png)

**Comment by andot** [comment]
电脑休眠的时候，你的服务肯定不执行啊。

**Comment by zhangruhong** [comment]
这个错是从休眠恢复后出现的 看有大神没有什么办法能不让他出现这个错误(比如catch后自己处理) 或者监听这个错误事件  我们找了很久 没有找到相应处理的配置

**Comment by andot** [comment]
休眠的时候网络都断掉了，醒来之后，客户端重建客户端，服务端重启服务。

**Comment by andot** [comment]
Hprose 3.0 for TypeScript 已经出来了。可以用 Hprose 3.0 for TypeScript 来代替 Hprose for Nodejs。3.0 提供了集群容错插件，设置该插件之后，如果网络出错，可以设置为自动重试。
