### ISSUE TITLE
Is io should be other repository.  like hprose-nodejs-io?

### ISSUE THREAD

**Issue by NathanLi** [hprose/hprose-nodejs#28]
This makes test case simple.

**Comment by andot** [comment]
如果不想全部写测试，只写部分测试也没问题啊，不需要单独分出来。一共也没有几K，放一块也不占空间，分多个包来包含感觉更麻烦。

**Comment by NathanLi** [comment]
单独分开不仅仅利于测试，也好分开管理的。
将 client、server、http 等都可抽成中间件模式，容易扩展。

**Comment by andot** [comment]
放在一起和分开跟是否容易扩展没有什么关系，一点影响都没有，倒是放在一起可以共享许多代码，而分开则很难做到，也就是说要说有影响也是分开反而不容易扩展。
