### ISSUE TITLE
syntaxError HarmonMaps.js: 'return' outside of function

### ISSUE THREAD

**Issue by 91jason** [hprose/hprose-nodejs#5]
我在使用 react native 开发移动应用，使用 npm install hprose 安装了2.0.8提示这个错误，为什么 ？
syntaxError HarmonMaps.js: 'return' outside of function

去除了 return 之后，还会提示找不到modules 'url' 与 'util'  why？

**Comment by andot** [comment]
我没用过 react native，难道是 react native 不兼容 javascript 语法吗？还有能说一下出错的行号吗？
