### ISSUE TITLE
代码后台运行的一些问题

### ISSUE THREAD

**Issue by taozhipeng1990** [hprose/hprose-nodejs#9]
我这边写的是客户端。如果直接node client.js的话。一直都没有问题。
但转入到后台运行。关掉窗口后。立马进程就被杀死。写其他的node都没有问题啊。
转到后台运行的方法有使用如下
1 nohup node --harmony-proxies client.js >/dev/null 2>&1 &
2 node --harmony-proxies client.js &

而且使用系统的计划任务。调用shell。 在shell内运行node --harmony-proxies client.js 没有任何效果。
请教大神,是不是 --harmony-proxies 的原因。
求解决方案

**Comment by andot** [comment]
你不用 --harmony-proxies 会有这个问题吗？

**Comment by taozhipeng1990** [comment]
对不起，昨天我检测到了问题。是log4js 使用了相对目录。所以.......
如果你是作者，建议升级下一个版本时，能否去掉--harmony-proxies
现在好像是必须使用--harmony-proxies   使用hprose时，加这个有抵触心里

**Comment by andot** [comment]
--harmony-proxies 不是必须的，你看一下文档就知道了。

**Comment by taozhipeng1990** [comment]
文档里只看到说可以不用加-proxies
英文不太好

**Comment by andot** [comment]
文档是中文的：https://github.com/hprose/hprose-nodejs/wiki/Hprose-%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by taozhipeng1990** [comment]
麻烦大神了。
我总是这么粗心太意。不好意思啊
